#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 15 19:18:13 2017

@author: wbreen
"""

def main():
    listComps()

def listComps():
    words = ['mary', 'had', 'a', 'little', 'lamb']
    words2 = ['mary', 'was', 'a', 'little', 'mary']
    
    print("Problem 1: ", [x[0:2] for x in words] )
    print("Problem 2: ", [x[0] for x in words if len(x) > 4])
    print("Problem 3: ", [len(x) > 4 for x in words])
    print("Problem 4: ", [(x.upper(), x.lower()) for x in words])
    print("Problem 5: ", [(words[x], words2[x]) for x in range(0, len(words)) if words[x] != words2[x]])
    print("Problem 6: ", [(x, y) for x in words for y in words2 if x==y])
    print("Problem 7: ", [x**2 for x in range(10)])
    print("Problem 8: ", [x*y for x in range(3) for y in range(3,5)])
    
main()